# GoReleaser configuration for bsubio CLI
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: bsubio
    main: ./cmd/bsubio
    binary: bsubio
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    # Ensure static binaries
    flags:
      - -trimpath

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}.sha256"
  algorithm: sha256

changelog:
  disable: false
  use: git
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: bsubio
    name: cli
  draft: false
  prerelease: auto
  mode: replace
  disable: false
  header: |
    ## bsubio CLI {{ .Tag }}

    Download the appropriate binary for your platform below.
  footer: |
    ---

    ### Installation

    #### Windows (Chocolatey)
    ```powershell
    choco install bsubio
    ```

    #### Quick Install (Recommended)
    ```bash
    curl -fsSL https://install.bsub.io/ | sh
    ```

    #### Manual Installation
    1. Download the binary for your platform
    2. Download the checksums file: `{{ .ProjectName }}_{{ .Version }}.sha256`
    3. Verify the checksum: `sha256sum -c {{ .ProjectName }}_{{ .Version }}.sha256`
    4. Make it executable: `chmod +x bsubio-*`
    5. Move to PATH: `sudo mv bsubio-* /usr/local/bin/bsubio`

    ### Documentation
    - [GitHub Repository](https://github.com/bsubio/cli)
    - [Documentation](https://docs.bsub.io)
  name_template: "{{.Tag}}"

chocolateys:
  - name: bsubio
    ids:
      - bsubio
    title: bsubio CLI
    authors: bsubio
    project_url: https://bsub.io
    url_template: "https://github.com/bsubio/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: https://bsub.io/favicon.ico
    copyright: 2025 bsubio
    license_url: https://github.com/bsubio/cli/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/bsubio/cli
    docs_url: https://app.bsub.io/static/docs/
    bug_tracker_url: https://github.com/bsubio/cli/issues
    tags: "cli batch-jobs job-scheduler cloud devops"
    summary: CLI for easy running heavy duty compute jobs in the cloud
    description: |
      bsubio CLI is a command-line tool for running heavy duty batch compute jobs and workflows on the bsubio cloud platform.

      Features:
      - Submit and manage CPU/GPU batch jobs 
      - Monitor job status and logs
      - Manage job types and configurations
      - Upload and manage job artifacts

      For more information, visit https://www.bsub.io
    release_notes: "https://github.com/bsubio/cli/releases/tag/{{ .Tag }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

# Announce releases (optional - uncomment if needed)
# announce:
#   slack:
#     enabled: true
#     message_template: 'bsubio CLI {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}'
